name: flutter_quesfity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  sqflite: ^2.0.0
  cloud_firestore: ^5.4.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_animation_progress_bar: ^2.3.1
  firebase_core: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
