// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhoL5JZ8Sx4h5xY6aIavE-dPsp3OyqWqg',
    appId: '1:179719611016:web:4c24df65b8f8c6f1e0353d',
    messagingSenderId: '179719611016',
    projectId: 'questifybanco',
    authDomain: 'questifybanco.firebaseapp.com',
    storageBucket: 'questifybanco.appspot.com',
    measurementId: 'G-3PCZY6SZ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqIgp1cyS8G9JfLLUcmMAf1FWkCLiD-20',
    appId: '1:179719611016:android:4cafd7c85a15704ee0353d',
    messagingSenderId: '179719611016',
    projectId: 'questifybanco',
    storageBucket: 'questifybanco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LSRtlSU8w1TVV-SH42sQSPupUhUr82k',
    appId: '1:179719611016:ios:fc4e1f0633c69868e0353d',
    messagingSenderId: '179719611016',
    projectId: 'questifybanco',
    storageBucket: 'questifybanco.appspot.com',
    iosBundleId: 'com.example.flutterQuesfity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LSRtlSU8w1TVV-SH42sQSPupUhUr82k',
    appId: '1:179719611016:ios:fc4e1f0633c69868e0353d',
    messagingSenderId: '179719611016',
    projectId: 'questifybanco',
    storageBucket: 'questifybanco.appspot.com',
    iosBundleId: 'com.example.flutterQuesfity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhoL5JZ8Sx4h5xY6aIavE-dPsp3OyqWqg',
    appId: '1:179719611016:web:87a41409e2039afee0353d',
    messagingSenderId: '179719611016',
    projectId: 'questifybanco',
    authDomain: 'questifybanco.firebaseapp.com',
    storageBucket: 'questifybanco.appspot.com',
    measurementId: 'G-LF2E8W62XY',
  );
}
